version: '2'
services:
  https:
    image: usertoken/haproxy
    container_name: haproxy
    environment:
      DOMAINS: usertoken.com,www.usertoken.com,me.usertoken.com,personal.usertoken.com,business.usertoken.com,graphql.usertoken.com,scuttlebot.usertoken.com
      EMAIL: admin@usertoken.com
      STAGING: "true"
      CONTINUE_ON_CERTONLY_FAILURE: "true"
    links:
      - www
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    volumes:
      - /netdisk/shared/work/docker/volumes/letsencrypt:/etc/letsencrypt
      - /netdisk/shared/work/docker/volumes/nginx/log:/var/log
      - /netdisk/shared/work/docker/volumes/cronstamps:/var/spool/cron/cronstamps

  www:
    image: jwilder/nginx-proxy
    container_name: www
    links:
      - www-usertoken-com
      - me-usertoken-com
      - dev-usertoken-com
      - personal-usertoken-com
      - business-usertoken-com
      - graphql-usertoken-com
      - scuttlebot-usertoken-com
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /netdisk/shared/work/docker/volumes/nginx/log:/var/log/nginx

  www-usertoken-com:
    image: usertoken/www.usertoken.com:1.0.0
    container_name: www-usertoken-com
    environment:
      - VIRTUAL_HOST=usertoken.com,www.usertoken.com

  me-usertoken-com:
    image: usertoken/www.usertoken.com:1.0.0
    container_name: me-usertoken-com
    environment:
      - VIRTUAL_HOST=me.usertoken.com

  dev-usertoken-com:
    image: usertoken/www.usertoken.com:1.0.0
    container_name: dev-usertoken-com
    environment:
      - VIRTUAL_HOST=dev.usertoken.com

  personal-usertoken-com:
    image: usertoken/www.usertoken.com:1.0.0
    container_name: personal-usertoken-com
    environment:
      - VIRTUAL_HOST=personal.usertoken.com

  business-usertoken-com:
    image: usertoken/www.usertoken.com:1.0.0
    container_name: business-usertoken-com
    environment:
      - VIRTUAL_HOST=business.usertoken.com

  graphql-usertoken-com:
    image: usertoken/www.usertoken.com:1.0.0
    container_name: graphql-usertoken-com
    environment:
      - VIRTUAL_HOST=graphql.usertoken.com

  scuttlebot-usertoken-com:
    image: usertoken/www.usertoken.com:1.0.0
    container_name: scuttlebot-usertoken-com
    environment:
      - VIRTUAL_HOST=scuttlebot.usertoken.com
