version: "2"
services:
    https:
        # XXX Use image: tecnativa/haproxy-letsencrypt instead
        build: .
        environment:
            # XXX: Fill this with your real data
            DOMAINS: example.com,example.org
            EMAIL: admin@example.com
            # XXX: Use "false" to get real certs!
            STAGING: "true"
            # XXX: Use "true" when cert fetching should fail (i.e. in dev env)
            CONTINUE_ON_CERTONLY_FAILURE: "false"
        links:
            - www
        ports:
            # It's important to have real ports handled by this container
            - "80:80"
            - "443:443"
        restart: unless-stopped
        volumes:
            # This keeps certs and cronstamps across reloads
            - letsencrypt:/etc/letsencrypt
            - cronstamps:/var/spool/cron/cronstamps

    # XXX: Put your web app here; for testing, this one is very useful
    www:
        image: stackatoapps/phpinfo

volumes:
    letsencrypt:
    cronstamps:
